# Generated by Django 4.1.2 on 2022-10-26 12:38

import aceitacao.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=256, validators=[aceitacao.validators.teste_nome])),
                ('data_de_nascimento_pet', models.DateField()),
                ('especie_pet', models.CharField(max_length=20)),
                ('raca_pet', models.CharField(max_length=20)),
            ],
        ),
    ]
