# Generated by Django 4.1.2 on 2022-10-26 12:38

import aceitacao.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_func', models.CharField(max_length=256, validators=[aceitacao.validators.teste_nome])),
                ('data_nascimento_func', models.DateField()),
                ('cpf_func', models.IntegerField(validators=[aceitacao.validators.teste_cpf])),
                ('rg_func', models.IntegerField(validators=[aceitacao.validators.teste_rg])),
                ('telefone_func', models.CharField(max_length=256, validators=[aceitacao.validators.teste_telefone])),
                ('email_func', models.CharField(max_length=256, validators=[aceitacao.validators.teste_email])),
            ],
        ),
    ]
