# Generated by Django 4.1.2 on 2022-11-09 18:52

import aceitacao.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf_func',
            field=models.IntegerField(unique=True, validators=[aceitacao.validators.teste_cpf]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento_func',
            field=models.DateField(validators=[aceitacao.validators.teste_data]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_func',
            field=models.CharField(max_length=256, unique=True, validators=[aceitacao.validators.teste_email]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo_func',
            field=models.CharField(max_length=256, validators=[aceitacao.validators.teste_nome, aceitacao.validators.teste_sem_numero]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg_func',
            field=models.IntegerField(unique=True, validators=[aceitacao.validators.teste_rg]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone_func',
            field=models.CharField(max_length=256, unique=True, validators=[aceitacao.validators.teste_telefone]),
        ),
    ]
